language: ruby
rvm:
- 2.3.4
cache: bundler
branches:
  only:
  - master
install:
- bundle install
script:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- JEKYLL_ENV=production jgd -u https://$ZHULIANG_GH_TOKEN@github.com/grab/engineering-blog.git
env:
  global:
  - secure: QBQhRtJyTrjQoGIyLRaeOm3+t+vMlDRcmnBHv/7bxY+UwXxnHoMhQlqxT68utD1v7kFuaqDaJ9sJJv8Ke5h/IC0fyYJcKsmt1mYSYoxo1nrRm5sJH1K565Nl8ytEtwHSiwJwJubAvfjJVH2PazzOTrR544DpLbJjD8J8g14G4/wnsC8Vagna86AyxV3SF89DXH5suf6RNATGcbTHhLuQyRHIpwfcYc5GbcTjpyLIYja9yFWAWgRvawRTx8hgOiI3VUQgWanW4lwV1b3No3IcNCR/A+6SbliXT+A4ckDv4u4cMDmrjhq9kINta+pQvATscIuQBpNDmkIUnSHtCbAGADRWJ4MuvlEkuT1r/w5OaBdnxiZDTguOfRpB8nZ0w+VyPok72Mhwb2b95lv90i9mS3CanNbTmJxfWhS8EqR2tE78JoS9OBR1kr1VBn7egfE5zzWEFVc+ngoC0CSh7Xdcw37yzsZEDKyeuT0AFLyKnG4TxglqLGka8I/PirFTrJ6N10BNBTSafTISzn8G53L/SrLgiGf7sY1bTneBve9a+Xpwzkuc73L6XWQ4w94K2ISe53dspoyn34aGawXyZp8IpnXn3bS+5thb0HhUbsqRUkX/WiHfgsJIhJCYnoCiXbk2hlrP/hjiA5Gltlj8E5syA0OpGRaH3w0nbaKmYp2JPsw=
