language: ruby
rvm:
- 2.3.4
cache: bundler
branches:
  only:
  - master
install:
- bundle install
script:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- JEKYLL_ENV=production jgd -u https://$YANGSHUN_GH_TOKEN@github.com/grab/engineering-blog.git
env:
  global:
  - secure: biS8UyL3fnMYXyJsSEV3jJmBHgcogs7jJcpxXl7pLW3kZWSyMVi/L9PooLiRu90pjmLYVDjNtONs2eK0Q6H5iN5lIWaMwpWhtkcrW71CnoAFcLcZEdmg+BxwMqjbIn75Tw/Uay7FPb0ioBhJzDT80TvbXHcqphaPBYJtCQfviefoXWNmnsiWMd6eQipL56St0YwPKdt7SZnr+dH31BLILRvchMw3JWkH3Tjcdonki2GBK8Wj61id70NIftWXCSjbAwq4+a4etblJ9z8eyg/x49YkZDSDB/rC9W2s2d7mN+lKMyCf6JxayB/gQd3elPtg8EsjTmtkgiUERKiNySxrDLzf5xrBsZMFWhoubMKxwHfTtlR2QT8Yw/RE/A57IVoVZ8pb/DD74k5U/GcgbHgGRXQhnKwJtU+/pv0OEXOvSxXlExF6waS8COis/RgwUXKtDuQynuIR9BuxQcyHxL0Ipc0zlPiJmltVVQMHkWL5LJpFqxX0MNOYyVO94eTMdgC4GSUEjQ5gRrqBiPcwWHPivFiWE1sC44kejm7zZVgKOoy3+aEmBNDmQtI0tmjf4EYZdX9goPF2QCipEO79d05422uyATW6LxUDOsvKnX2r6k9Soh6ykahPq6FU86r8ErNLhX/5SjT6LvjWE5vCJCYdrXzrKtsBEDehoHUleDA+XaU=
