# Site settings
title: Grab Engineering
email: engineering.blog@grab.com
description: > # this means to ignore newlines until "baseurl:"
  Hey there! We hope you have enjoyed using Grab so far. Keep
  up with our latest updates on our blog. Subscribe using the RSS button!
url: https://grab.github.io # the base hostname & protocol for your site
facebook_username: grab.engineering
twitter_username: GrabSG
github_username:  grab

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
paginate: 5
encoding: UTF-8
