# Site settings
title: Grab Engineering
email: engineering.blog@grab.com
description: > # this means to ignore newlines until "url:"
  Hey there! We hope you have enjoyed reading Grab Engineering blog so far. Keep
  up with our latest updates on our blog. Subscribe using the RSS button!
url: https://grab.github.io # the base hostname & protocol for your site

social_media:
  facebook: grab.engineering
  github:  grab

# Post settings
post:
  date_format: '%-d %b %Y'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
paginate: 5
encoding: UTF-8
