# Site settings
title: Grab Engineering
email: engineering.blog@grab.com
description: > # this means to ignore newlines until "url:"
  Grab's Engineering team solves critical transportation challenges and makes
  transport freedom a reality for 620 million people in Southeast Asia.
url: http://engineering.grab.com # the base hostname & protocol for your site

social_media:
  facebook: grabengineering
  github:  grab
  twitter: grabengineering

disqus:
  shortname: grabengineering

google_analytics_id: UA-73060858-2

# Post settings
post:
  date_format: '%-d %b %Y'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
paginate: 5
encoding: UTF-8
